language: python
python:
  - "3.5"
  - "3.6"
notifications:
  email: false
install: 
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coveralls
script: 
  - coverage run -m pytest tests --cov meetup_facebook_bot
after_success:
  - coveralls
